### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "aryo",
    "email": "aryo@mail.com",
    "password": "aryo123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "aryo@mail.com",
    "password": "aryo123"
}

### Who Am I
GET http://localhost:3000/api/auth/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhcnlvQG1haWwuY29tIiwibmFtZSI6ImFyeW8iLCJwcm9maWxlX3BpY3R1cmVfdXJsIjpudWxsLCJpYXQiOjE3MTA5OTk3NTB9.j3G9kMM5ShPDMliA99Iw2crHs4Tx_LlaBv9Ji3a2bC4

### Course Create
POST http://localhost:3000/api/courses
Content-Type: application/json

{
    "name": "Sistem Informasi",
    "description": "semua tentang sistem informasi"
}

### Courses
GET http://localhost:3000/api/courses

### Courses Detail
GET http://localhost:3000/api/courses/1

### Lesson Create
POST http://localhost:3000/api/lessons
Content-Type: application/json

{
    "title": "Postgres",
    "body": "belajar database postgre sql",
    "course_id": 1
}