openapi: "3.0.0"
info:
  title: PBL Micro Learning
  description: PBL Micro Learning
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
  - url: https://pbl-micro-learling.up.railway.app/api
security:
  - bearerAuth: []
paths:
  /auth/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: aryo
                email:
                  type: string
                  example: aryo@mail.com
                password:
                  type: string
                  example: aryo123
              required:
                - name
                - email
                - password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
  /auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: aryo@mail.com
                password:
                  type: string
                  example: aryo123
              required:
                - email
                - password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
  /auth/whoami:
    get:
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BasicResponse"
                  - type: object
                    properties:
                      data:
                        type: object
components:
  schemas:
    BasicResponse:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
        error:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  
